"""FileStore mutable state: stdlib sqlite3 (investigations, plans, approvals, tasks, audit, notes, notebook, memory additions).

Facts live in pickled DataFrames under data/store/<seed>/ (generated by data/generator.py).
Audit log is a sha256 hash chain: hash = sha256(prev_hash || canonical(row)).
"""

from __future__ import annotations

import hashlib
import os
import json
import sqlite3
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .config import SIM_NOW, STORE_DIR

DB_PATH = Path(os.environ.get("STRATA_STATE_DB", str(STORE_DIR / "state.db")))
_lock = threading.RLock()

SCHEMA = """
create table if not exists docs (collection text, id text, json text, primary key (collection, id));
create table if not exists audit_log (id integer primary key autoincrement, at text, wall_at text, actor_type text,
  actor text, action text, entity_type text, entity_id text, detail text, prev_hash text, hash text);
create table if not exists notebook_entries (id integer primary key autoincrement, created_at text, author text,
  tried text, happened text, changed text, evidence text);
"""


def conn() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    c = sqlite3.connect(DB_PATH, check_same_thread=False)
    c.row_factory = sqlite3.Row
    c.executescript(SCHEMA)
    return c


_C = conn()


def wall_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def put(collection: str, id_: str, doc: dict[str, Any]) -> None:
    with _lock:
        _C.execute("insert or replace into docs values (?,?,?)", (collection, id_, json.dumps(doc, default=str)))
        _C.commit()


def get(collection: str, id_: str) -> dict[str, Any] | None:
    with _lock:
        r = _C.execute("select json from docs where collection=? and id=?", (collection, id_)).fetchone()
    return json.loads(r[0]) if r else None


def all_(collection: str) -> list[dict[str, Any]]:
    with _lock:
        rows = _C.execute("select json from docs where collection=? order by rowid", (collection,)).fetchall()
    return [json.loads(r[0]) for r in rows]


def next_id(collection: str) -> int:
    with _lock:
        r = _C.execute("select count(*) from docs where collection=?", (collection,)).fetchone()
    return int(r[0]) + 1


def canonical(row: dict[str, Any]) -> str:
    return json.dumps(row, sort_keys=True, separators=(",", ":"), default=str)


def audit(actor_type: str, actor: str, action: str, entity_type: str, entity_id: str,
          detail: dict[str, Any] | None = None, at: str | None = None) -> dict[str, Any]:
    with _lock:
        prev = _C.execute("select hash from audit_log order by id desc limit 1").fetchone()
        prev_hash = prev[0] if prev else "GENESIS"
        row = {"at": at or SIM_NOW.isoformat(), "wall_at": wall_now(), "actor_type": actor_type, "actor": actor,
               "action": action, "entity_type": entity_type, "entity_id": str(entity_id), "detail": detail or {}}
        h = hashlib.sha256((prev_hash + canonical(row)).encode()).hexdigest()
        cur = _C.execute("insert into audit_log (at,wall_at,actor_type,actor,action,entity_type,entity_id,detail,prev_hash,hash)"
                         " values (?,?,?,?,?,?,?,?,?,?)",
                         (row["at"], row["wall_at"], actor_type, actor, action, entity_type, str(entity_id),
                          json.dumps(detail or {}, default=str), prev_hash, h))
        _C.commit()
        row.update({"id": cur.lastrowid, "prev_hash": prev_hash, "hash": h})
        return row


def audit_rows() -> list[dict[str, Any]]:
    with _lock:
        rows = _C.execute("select * from audit_log order by id").fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["detail"] = json.loads(d["detail"] or "{}")
        out.append(d)
    return out


def verify_chain() -> dict[str, Any]:
    prev = "GENESIS"
    rows = audit_rows()
    for r in rows:
        row = {k: r[k] for k in ("at", "wall_at", "actor_type", "actor", "action", "entity_type", "entity_id", "detail")}
        h = hashlib.sha256((prev + canonical(row)).encode()).hexdigest()
        if r["prev_hash"] != prev or r["hash"] != h:
            return {"ok": False, "checked": len(rows), "first_bad_id": r["id"]}
        prev = r["hash"]
    return {"ok": True, "checked": len(rows), "first_bad_id": None}


def reset_simulated() -> None:
    """Restore simulated state. Never deletes notebook entries or human-authored memory/notes."""
    with _lock:
        humans = [d for d in all_("memory_added") if not str(d.get("authored_by", "")).startswith(("strata-system", "DRAFT"))]
        human_notes = all_("notes")
        _C.execute("delete from docs where collection not in ('notes')")
        _C.execute("delete from audit_log")
        _C.commit()
        for d in humans:
            put("memory_added", d["ref"], d)
        _ = human_notes


def notebook_list() -> list[dict[str, Any]]:
    with _lock:
        return [dict(r) for r in _C.execute("select * from notebook_entries order by id desc").fetchall()]


def notebook_add(author: str, tried: str, happened: str, changed: str | None, evidence: str | None) -> dict[str, Any]:
    with _lock:
        cur = _C.execute("insert into notebook_entries (created_at,author,tried,happened,changed,evidence) values (?,?,?,?,?,?)",
                         (wall_now(), author, tried, happened, changed, evidence))
        _C.commit()
        return {"id": cur.lastrowid}


Path  # keep import used for type checkers
