/** Short definitions for `TermHint` (`?` popovers) and the /app/help glossary. Lane L6 owns the wording. Keep each under 40 words. */
export const TERMS: Record<string, { term: string; text: string }> = {
  baseline: { term: "Baseline", text: "This account's own normal: the typical value of the same 4-week measure over its last two years, adjusted for season. STRATA compares each account with itself, never with other accounts." },
  robust_z: { term: "Robust z-score", text: "How unusual the last 4 weeks are against the account's normal spread: (value − median) ÷ (1.4826 × median absolute deviation). Beyond 2 counts as a warning; beyond 3 is very unusual." },
  evidence_id: { term: "Evidence ID", text: "A label for one computed signal, for example EV-4821-order_volume_delta. Every sentence STRATA writes must cite one, and every number in it must appear in that evidence, or the sentence is dropped." },
  blast_radius: { term: "Blast radius", text: "Other accounts hit by the same cause, for example other buyers of the short product whose fill rate on it fell below 0.92. They may not have complained yet." },
  similarity: { term: "Similarity breakdown", text: "How close a past case is to this one: 0.5 × text match (TF-IDF) + 0.3 × same cause + 0.2 × same signal pattern. The breakdown is shown so you can judge it." },
  provenance: { term: "Provenance", text: "Where a number comes from: computed (from the synthetic data), synthetic (generated), illustrative (scripted, for demonstration) or assumption (a stated guess). Every number carries one badge." },
  four_eyes: { term: "Four-eyes", text: "Two different people must approve. Used for quality and possible patient-safety cases, which only the QA Head may approve." },
  risk_score: { term: "Risk score", text: "0–100. Independent warning signals combined (noisy-OR), then scaled by how many separate systems agree. One or two systems alone can never go above 'elevated'. It is not a probability of loss." },
  exposure: { term: "Revenue exposure", text: "The account's normal 12-week order value. It shows what is at stake, not a forecast of what will be lost." },
  silent_period: { term: "Silent period", text: "Days a problem existed before an assumed weekly manual review (flags a month-on-month drop over 25%) would catch it. Labelled assumption: the review rule is not measured." },
  alert_budget: { term: "Alert Budget", text: "At most 7 items per role per day, ranked by exposure × confidence × urgency. The rest are listed as held back with the reason, so nothing is hidden." },
  noisy_or: { term: "Noisy-OR", text: "A way to combine independent warnings: each gives a chance p; combined = 1 − (1 − p1) × (1 − p2) × … Several weak but independent warnings add up; one strong warning cannot be double-counted." },
  source_diversity: { term: "Source diversity", text: "How many separate systems (orders, inventory, support, CRM, finance, workforce) agree. Risk is scaled by 0.55 for one, 0.80 for two and 1.00 for three or more." },
  severity_bands: { term: "Severity bands", text: "Healthy under 30, watch 30–49, elevated 50–69, high 70–84, critical 85+. High and critical need 3 or more systems agreeing. An incident opens at 50." },
  seasonality: { term: "Seasonality adjustment", text: "Orders are divided by a week-of-year index from the prior year, so a normal festival dip is not mistaken for a problem." },
  common_mode: { term: "Common-mode adjustment", text: "If more than 60% of accounts move the same way in the same weeks, the shared move is removed first. A market-wide dip is not an account problem." },
  hold_out: { term: "Hold-out seed", text: "A second synthetic data set from the same generator with a different random draw, never used for tuning. It checks over-fitting; it is not independent real-world validation." },
  time_to_action: { term: "Time-to-action", text: "Real wall-clock seconds from the detection record to a human approval record in the audit trail. It measures clicks in this prototype, not a field process." },
  standing_routine: { term: "Standing routine", text: "A repeating job (RT01–RT04) a human approves once. It runs only on the simulated clock and only creates internal tasks, drafts, digests and notes." },
  replay_mode: { term: "Replay mode", text: "The engine serves recorded responses from a snapshot, with no data store, keys or network. It refuses changes. Used as a stage fallback." },
  data_health_guard: { term: "Data Health Guard", text: "If a feed is older than 3× its expected interval, its signals pause everywhere. If an account's order load has over 5% duplicate rows, that account's order signals pause." },
  isolation_forest: { term: "IsolationForest check", text: "An unsupervised model (200 trees, 5% contamination) over each account's signal z-scores. Shown on Evaluation as a second opinion only; it never decides detection." },
  witness: { term: "Witness", text: "One adverse signal from one system. Each witness contributes p = weight × min(1, |robust z| ÷ 4) to the risk score." },
  route_only: { term: "Route-only", text: "Quality and possible adverse-event cases: STRATA only routes them to the QA Head with four-eyes approval. It gives no clinical advice and drafts nothing patient-facing." },
  simulated_task: { term: "Simulated task", text: "A task or message draft created when a plan is approved. In this prototype nothing is sent: no email, WhatsApp or webhook leaves the machine." },
};
